### ISSUE TITLE
Error in node_modules folder 

### ISSUE THREAD

**Issue by JonathanOJ** [unlayer/angular-email-editor#127]
Im trying to use  your lib in the version 15 of Angular, but when i start the project explode this error in the node_modules:

error TS2688: Cannot find type definition file for 'unlayer-types/embed'.
/// <reference types="unlayer-types/embed" />

Cannot find module 'embed/index' or its corresponding type declarations.
import Embed from 'embed/index';

Cannot find module 'embed/Editor' or its corresponding type declarations.
3 import { Editor as EditorClass } from 'embed/Editor';

Cannot find module 'state/types/types' or its corresponding type declarations.
4 import { JSONTemplate as JSONTemplateType, ToolsConfig as ToolsConfigInterface } from 'state/types/types';

It includes everything needed and what the documentation wants, I import the module and script in index.html:
<script src="//editor.unlayer.com/embed.js"></script>

**Comment by omerzahidbajwa** [comment]
please try with `"skipLibCheck": true` flag under tsconfig.json->compilerOptions, we are working on a fix for our typescript support lib

**Comment by JonathanOJ** [comment]
Its works! Thanks
