### ISSUE TITLE
Request - Update to Angular 18

### ISSUE THREAD

**Issue by Kikovenu** [unlayer/angular-email-editor#137]
Could you please upgrade to 18? and guide us to work in Angular 18.

**Comment by Kikovenu** [comment]
Hello,
Any updates?
Please respond

**Comment by omerzahidbajwa** [comment]
Hi, are you facing any specific issue? the latest version seems to be compatible with angular 18

**Comment by Kikovenu** [comment]
Thanks 
It is working

**Comment by Kikovenu** [comment]
Appreciate
