### ISSUE TITLE
errors with node module dependencies

### ISSUE THREAD

**Issue by etnmoussillac** [unlayer/angular-email-editor#140]
I did `npm install angular-email-editor --save` to install the module, but after doing `npm i` it gives me a lot of dependency errors, such as 
`TS2307: Cannot find module 'react-redux' or its corresponding type declarations. ` or `npm i --save @fortawesome/free-solid-svg-icons
`.

I tried installing these modules one by one but for some I can't seem to find the exact ones, but I feel like this is not what I should do, is there something I am missing?

**Comment by omerzahidbajwa** [comment]
Hi, please try `skipLibCheck: true` in tsconfig.json

**Comment by etnmoussillac** [comment]
Thank you sir that fixed my issue
