### ISSUE TITLE
Could not find a valid element for given id or className

### ISSUE THREAD

**Issue by jayanthbondi** [unlayer/angular-email-editor#32]
I'm using a react version of 16.13.1, while rendering EmailEditor of version 1.1.1, I'm getting the above issue.
Can someone help me it.

Thanks in advance

**Comment by azarus** [comment]
@adeelraza the issue still exists and you closed the issue without giving further answer or reference? Can we get an answer on why we're getting this error at least so we don't have to dig into the code.
There's only a PR but no solution, we're using the latest version and it seems to be broken.

Thank you!
