### ISSUE TITLE
upload images

### ISSUE THREAD

**Issue by JonathanRamosNascimento** [unlayer/angular-email-editor#34]
is it possible to save the images on my s3 or my upload folder of the angular project itself?

**Comment by bruno-brandao** [comment]
any news about that?

**Comment by JonathanRamosNascimento** [comment]
not bro

**Comment by bruno-brandao** [comment]
Já que você é brasileiro vou responder em português.

Para usar o seu próprio storage S3 você tem que criar uma conta no dashboard [Unlayer](https://dashboard.unlayer.com/), após criar sua conta você pode configurar o seu storage lá como diz aqui https://docs.unlayer.com/docs/amazon-s3 na documentação.

Após esse processo, basta você colocar o **projectId** no objeto **options**.

Para encontrar o projectId basta você ir em settings no menu e na aba Embed e lá estará o seu projectId ou você pode pegar na URL do dashboard após o login.

Valeu!!

**Comment by JonathanRamosNascimento** [comment]
Vllw mano heheh
