### ISSUE TITLE
When `editorId` is not provided error is raised

### ISSUE THREAD

**Issue by KrakenTyio** [unlayer/angular-email-editor#65]
![Screenshot from 2021-06-22 12-28-03](https://user-images.githubusercontent.com/5727376/122909311-5bc12e80-d355-11eb-96b9-7423d5cf6e7b.png)

adding `editorId` prevent this error, which should be optional
`<email-editor #editor editorId="email-editor" (loaded)="editorLoaded()" [options]="options"></email-editor>`

**Comment by dwaravijaykumar** [comment]
getting same issue when with Angular. Any one could help on this?

**Comment by KrakenTyio** [comment]
Add editorId input for email-editir component
In doc its optional but in fact its mandatory

**Comment by dwaravijaykumar** [comment]
Could you please provide me the sample code for providing the Id?
