### ISSUE TITLE
Two way binding ngmodel is not working 

### ISSUE THREAD

**Issue by MrSatyam77** [unlayer/angular-email-editor#89]
This editor two way binding is not working how I am binding data in update time I need to display preview once user update data

ngModel and formcontrol is not working 

<email-editor ngDefaultControl [(ngModel)]="emailTemplate.templatestring"
  name="templatestring" #templatestring="ngModel" [ngClass]="{'is-invalid': f.submitted && templatestring.invalid}" />

**Comment by dvdnhm** [comment]
I believe you need to call exportHTML to get the current design.

`this.emailEditor.editor.exportHtml((data: any) => {
  message.htmlMessage = data.html;
  message.unlayerDesign = data.design;
});`

**Comment by MrSatyam77** [comment]
data.design is working for me thanks @dvdnhm
