### ISSUE TITLE
How to make this work for angularjs

### ISSUE THREAD

**Issue by aramidefemi** [unlayer/angular-email-editor#9]

**Comment by carlo-arellano** [comment]
I'm also looking for this one since most of our app are in AngularJS.

**Comment by schimini** [comment]
@aramidefemi This lib is unlayer's wrapper for angular and i don't think it's possible to use in angularjs the way you expect. If no one ever ports this to angularjs ( which honestly i don't believe to be worth it ) you should stick with using the standalone unlayer library [docs](https://docs.unlayer.com/docs/getting-started) without any wrapper library.

**Comment by schimini** [comment]
@adeelraza This is a good example of a closable issue in my opinion ✔️

**Comment by aramidefemi** [comment]
> @aramidefemi This lib is unlayer's wrapper for angular and i don't think it's possible to use in angularjs the way you expect. If no one ever ports this to angularjs ( which honestly i don't believe to be worth it ) you should stick with using the standalone unlayer library ([docs here](https://docs.unlayer.com/docs/getting-started)) without any wrapper library.

using the standalone unlayer library -  is exactly what i'm doing at the moment thank you.
